### ISSUE TITLE
BUG: potential heatmap errors for test case with buggy log data

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#730] opened 2022-05-04 19:48 UTC
See details of Python errors in https://github.com/darshan-hpc/darshan-logs/pull/35.

They seem to imply a shape mismatch in heatmap module data, though I did not see anything obviously wrong in terms of inconsistent heatmap shapes across processes when scanning the log records (should check programmatically to confirm). It's also worth noting that this example log shows general corruption or overflow of heatmap counters, so it does seem reasonable that heatmap parameters could be inconsistent somewhere, leading to the error. We should figure out whether the issue is related to corruption of module data at runtime, or if there is a subtle bug in PyDarshan code.

**Comment by tylerjereddy** [comment] 2022-05-04 22:12
@shanedsnyder 

On the `pydarshan` side, this is what I think is happening with that tensorflow log:

There are 18 MPI ranks, but 6 of them are completely inactive, so we get a shape mismatch between `nprocs` (*all* 18 ranks according to the darshan bindings) used for y-axis, and the data present in the `STDIO` heatmap dataframe (*only* 12 ranks).

This doesn't cause a crash for the original DXT control flow, because that goes through `get_heatmap_df()`, which has a pandas `reindex` operation that adds inactive ranks back in as all-zero rows.

So, suggested path forward:

1. I should make a much smaller/simpler reproducing log file with a i.e., a few active ranks and one or two inactive ranks, with `HEATMAP` monitoring turned on.
2. Write a reproducing test with that smaller log file.
3. Add a reindex operation to the `HEATMAP` control flow somewhere to fix the bug (basically, include inactive ranks as all-zero rows in the data structure).

**Comment by tylerjereddy** [comment] 2022-05-10 17:35
Looks like the third rank (rank 2) writes about 42 GB of data before the DXT POSIX stops recording it, while HEATMAP allows it to go right to the end, writing about 200 GB of data. Curiously though, the overflow in HEATMAP is on rank 1, not the rank writing tons of data, which we previously observed. I do see a divide by zero happening in the float processing for DXT POSIX somewhere, and there is an integer vs. float thing going on here too. I'll probably just focus on the matter of the overflow though, I'll see if I can get some `printf` traction there or something.


```
{'POSIX': {'len': 14553, 'ver': 4, 'idx': 1, 'partial_flag': False, 'num_records': 232}, 'STDIO': {'len': 228, 'ver': 2, 'idx': 8, 'partial_flag': False, 'num_records': 4}, 'DXT_POSIX': {'len': 656513, 'ver': 1, 'idx': 9, 'partial_flag': True, 'num_records': 164}, 'HEATMAP': {'len': 2317, 'ver': 1, 'idx': 14, 'partial_flag': False}}
hmap_df:
       (0.0, 3.2000000000000006]  (3.2000000000000006, 6.400000000000001]  (6.400000000000001, 9.600000000000001]  (9.600000000000001, 12.800000000000002]  ...  (601.6000000000001, 604.8000000000001]  (604.8000000000001, 608.0000000000001]  (608.0000000000001, 611.2000000000002]  (611.2000000000002, 614.4000000000001]
rank                                                                                                                                                       ...                                                                                                                                                                
0                             0                                    43908                               190015744                                   391688  ...                                       0                               618573052                                       0                                       0
1                             0                                    43908                               190015744                     -9223372036854384644  ...                                56971718                                       0                                       0                               401804384
2                    1451681294                               1407726370                              1456424543                               1402727039  ...                              1229382415                              1275831994                              1275840930                                       0

[3 rows x 192 columns]
hmap_df.sum(axis=1):
 rank
0            11864867373
1   -9223372025632112335
2           212472956120
dtype: int64
suspected overflow values in POSIX HEATMAP: [-9223372036854384644]
/Users/treddy/python_venvs/python_381_venv/lib/python3.8/site-packages/pandas/core/arraylike.py:364: RuntimeWarning: divide by zero encountered in divide
  result = getattr(ufunc, method)(*inputs, **kwargs)
hmap_df:
       (0.0, 3.058598792552948]  (3.058598792552948, 6.117197585105896]  (6.117197585105896, 9.175796377658845]  (9.175796377658845, 12.234395170211792]  ...  (599.4853633403778, 602.5439621329308]  (602.5439621329308, 605.6025609254838]  (605.6025609254838, 608.6611597180366]  (608.6611597180366, 611.7197585105896]
rank                                                                                                                                                     ...                                                                                                                                                                
0                 0.000000e+00                            4.390800e+04                            1.898693e+08                             5.671310e+05  ...                               5293158.0                            1.152839e+08                            5.032891e+08                                     0.0
1                 0.000000e+00                            4.390800e+04                            1.899301e+08                             5.063141e+05  ...                             117908287.0                            1.456090e+07                            0.000000e+00                             401804384.0
2                 1.451681e+09                            1.407726e+09                            1.456425e+09                             1.402727e+09  ...                                     0.0                            0.000000e+00                            0.000000e+00                                     0.0

[3 rows x 200 columns]
suspected overflow values in DXT_POSIX: []
max value in DXT_POSIX: 1456424543.0
min value in DXT_POSIX: 0.0
hmap_df.sum(axis=1):
 rank
0    1.186490e+10
1    1.122269e+10
2    4.232891e+10
dtype: float64
```

**Comment by carns** [comment] 2022-08-01 19:36
@tylerjereddy do you think this issue is resolved now with that PR merge?

**Comment by tylerjereddy** [comment] 2022-08-02 17:10
@carns yep, we've fixed both the Python and runtime/C sides of this problem now along with regression tests (well, the C regression tests aren't merged yet, but that's another can of worms)

**Closed by tylerjereddy** 2022-08-02 17:10 UTC
Labels: pydarshan
