### ISSUE TITLE
Memory leak in PyDarshan

### ISSUE THREAD

**Issue by jesse-r-s-hines** [darshan-hpc/darshan#811] opened 2022-09-14 16:45 UTC
There appears to be a memory leak in the PyDarshan package, causing the Python process to increase memory usage until it is killed, usually in under a minute.

## Steps to reproduce
The leak occurs when either trying to parse a very large `.darshan` file (≈1G), or simply opening and closing many smaller `.darshan` files in sequence.

```python
import darshan
import darshan.backend.cffi_backend as backend

def low_level(report_file):
    log = backend.log_open(report_file)
    rec = backend.log_get_generic_record(log, 'POSIX')
    while rec != None:
        rec = backend.log_get_generic_record(log, 'POSIX')
    backend.log_close(log)

def high_level(report_file):
    with darshan.DarshanReport(report_file, read_all=False, lookup_name_records=False) as report:
        for row in report.mod_records('POSIX'):
            pass

# These loops will leak memory.
# If the darshan files are large it take much fewer iterations to run out of RAM
for i in range(1_000_000):
    low_level('darshan_files/sample.darshan')
for i in range(1_000_000):
    high_level('darshan_files/sample.darshan')

# Actually, just opening the file will leak some as well.
for i in range(1_000_000):
    with darshan.DarshanReport('darshan_files/sample.darshan',
        read_all=False, lookup_name_records=False
    ) as report:
        pass

# Breaking down the backend method calls in `DarshanReport.open`

# Leaks
for i in range(1_000_000):
    log = backend.log_open('darshan_files/sample.darshan')
    backend.log_get_mounts(log)
    backend.log_close(log)

# Very slow leak here
for i in range(1_000_000):
    log = backend.log_open('darshan_files/sample.darshan')
    backend.log_get_modules(log)
    backend.log_close(log)

# These don't leak
for i in range(1_000_000):
    log = backend.log_open(report_file)
    backend.log_get_job(log)
    backend.log_get_exe(log)
    backend.log_close(log)
```

I don't see the issue when calling `darshan-parser` CLI, even on very large `.darshan` files `darshan-parser` will stay under 1-2G of memory usage.

I'm running on an Ubuntu 20.04 machine with 16G of RAM, with Python3.9.14 and PyDarshan 3.4.0.1. I've also reproduced the issue on PyDarshan 3.3.1.1.

The issue appears to occur with any `.darshan` file, but I've still uploaded a small [sample darshan log](https://github.com/darshan-hpc/darshan/files/9568265/sample.darshan.zip).

**Comment by tylerjereddy** [comment] 2022-09-15 15:51
Profiling the memory usage with `memory_profiler` I can reproduce a leak that seems to come from the `malloc` that is inside `darshan_log_get_modules()`, since CFFI likely doesn't own that memory scoped inside a C function. I'll see if I can patch it today and I may ask you to test my patch.

```python
import time

import darshan
import darshan.backend.cffi_backend as backend

def low_level(report_file):
    log = backend.log_open(report_file)
    rec = backend.log_get_generic_record(log, 'POSIX')
    backend.log_close(log)

if __name__ == "__main__":
    start = time.perf_counter()
    for i in range(100000):
        low_level('darshan_files/sample.darshan')
    end = time.perf_counter()
    print("Script complete in", end - start, "sec")

```

```bash
rm *.dat
mprof run test.py
mprof plot
```

![image](https://user-images.githubusercontent.com/7903078/190449362-59d6ec72-c67f-419c-a387-7437cff0f4f4.png)

**Comment by jesse-r-s-hines** [comment] 2022-09-15 16:23
Great, thanks!

**Comment by tylerjereddy** [comment] 2022-09-15 16:49
I think you're right that there is more than 1 leak, gh-813 seems to get rid of one of them to cut it in ~half for the leak script I use, above. I'll probably try to investigate the others (file opening related leaks?) separately.

**Comment by tylerjereddy** [comment] 2022-09-15 19:20
I also reproduced the more serious memory leak you described above for `log_get_mounts()`, using the feature branch for gh-813 and modified version of script above we hit a ridiculous 3.5 GB for this tiny file:

![image](https://user-images.githubusercontent.com/7903078/190490515-d54d9022-8b36-4c43-b366-1535e2913297.png)

Reproducer modifications vs. https://github.com/darshan-hpc/darshan/issues/811#issuecomment-1248290837:

```diff
--- a/test.py
+++ b/test.py
@@ -5,7 +5,7 @@ import darshan.backend.cffi_backend as backend
 
 def low_level(report_file):
     log = backend.log_open(report_file)
-    rec = backend.log_get_generic_record(log, 'POSIX')
+    rec = backend.log_get_mounts(log)
     backend.log_close(log)

```

Shane also pointed this one out this morning after the first `malloc()`-related discussion we had--I'll see if I can get this one patched as well (there is probably still at least one other leak, but not sure yet).

**Comment by tylerjereddy** [comment] 2022-09-15 21:07
For the leak remaining at https://github.com/darshan-hpc/darshan/pull/813#issue-1374812967, I don't immediately see where the memory is accumulating. Certainly, it is the result of `rec = backend.log_get_generic_record(log, 'POSIX')`, and `STDIO` also leaks on that same call. I see that `darshan_log_get_record` hides calls to various functions, so it may take a bit longer to track that one down.

I also note that, although they don't appear to be involved in the reproducers I've seen so far, `darshan_log_get_name_records()` and `darshan_log_get_filtered_name_records` both seem to have the same malloc/leak-prone idiom.

**Comment by shanedsnyder** [comment] 2022-09-27 17:58
I think we have the 3 memory leaks we identified here all sorted out and merged into our `main` branch -- thanks @tylerjereddy for hacking on that and thanks @jesse-r-s-hines for the report.

If you're up for trying the fix, you can try building PyDarshan from source based on our current `main` branch. These fixes should ultimately be included in an upcoming release (3.4.1.0), but that may be another month or so.

**Comment by jesse-r-s-hines** [comment] 2022-09-27 22:04
I've done some testing from the `main` branch and am not seeing any leaks. Thanks!

**Comment by shanedsnyder** [comment] 2022-09-28 00:34
Great, thanks for confirming! I'll go ahead and close this, but please keep us posted if you run into any more issues.

**Closed by shanedsnyder** 2022-09-28 00:34 UTC
Labels: bug, pydarshan
