### ISSUE TITLE
new I/O cost summary figures not displaying I/O time for example log

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#590] opened 2021-12-14 18:00 UTC
The following log file gives unexpected results on the branch used in PR #571 
[anon.darshan.gz](https://github.com/darshan-hpc/darshan/files/7713754/anon.darshan.gz)

This log contains POSIX records which total to nearly 1 second of I/O time (snipped some out from `darshan-parser --total`:
```
total_POSIX_F_READ_TIME: 0.281718
total_POSIX_F_WRITE_TIME: 0.504260
total_POSIX_F_META_TIME: 0.170138
```

The I/O cost plots are blank for me when generating a job summary using that branch, though:
![image](https://user-images.githubusercontent.com/24571836/146053988-76faa4e2-3db2-4ee6-a597-c3ada8b75c47.png)

**Comment by nawtrey** [comment] 2021-12-14 18:23
Here is some output I’ve generated from the log Shane provided: 
```
Module: STDIO
nprocs: 1

DataFrame (before averaging):
        Read     Write      Meta
0   0.000000  0.165090  0.000000
1   0.000000  0.000779  0.000000
2   0.231976  0.000000  0.000057
3   0.000000  0.000000  0.000049
4   0.000070  0.000016  0.000705
5   0.000000  0.000000  0.000278
6   0.000000  0.000000  0.068633
7   0.000081  0.000000  0.002266
8   0.000000  0.000097  0.000629
9   0.000045  0.000000  0.000051
10  0.000214  0.000000  0.000083

Sum of all values:  0.47111964225769043

Final (average) values:
Read     0.021126
Write    0.015089
Meta     0.006614
```
With a runtime of 30 seconds, even if we took the sum of all of the `STDIO` Read/Write/Meta values, we would only get 0.47/30s (1.5%). So with the average we get more like 0.15%, which is apparently too small to see. 

The `POSIX` data is even more extreme:
```
Module: POSIX
nprocs: 1

DataFrame (before averaging):
        Read     Write      Meta
0   0.000000  0.000000  0.000033
1   0.000000  0.000000  0.000017
2   0.000000  0.000000  0.000016
3   0.000041  0.000000  0.000064
4   0.000008  0.000000  0.000033
..       ...       ...       ...
76  0.000067  0.011486  0.001358
77  0.000066  0.023593  0.001167
78  0.000000  0.000000  0.000080
79  0.000000  0.001935  0.001513
80  0.000000  0.000000  0.000026

[81 rows x 3 columns]

Sum of all values:  0.9561164379119873

Final (average) values:
Read     0.003478
Write    0.006225
Meta     0.002100
```
So I get ~1s of total runtime, but divided by 81 we get an even smaller value than for `STDIO`… 

This is what I would expect for this case based on my original understanding of this calculation, but I think the issue is I am _averaging_ over the records when I should be _summing_ them. So there is effectively an unnecessary division by the number of records.

**Comment by tylerjereddy** [comment] 2021-12-14 18:28
What would your "original understanding" provide that is useful/sensible compared to what Shane is expecting?

**Comment by tylerjereddy** [comment] 2021-12-14 18:29
Shane reports a smilar bug for `acme_fcase_trace` as well (in logs repo I think).

**Comment by shanedsnyder** [comment] 2021-12-14 18:31
Yeah, we just need to get rid of the additional division by the number of records.

For the average calculation, all you want is to sum up each component (read/write/meta) over all file records (I guess 81 for this case), then divide by the total number of processes. This figure is meant to convey how much time was spent doing I/O across all files an application accesses, no need to further average in terms of number of files accessed.

**Comment by nawtrey** [comment] 2021-12-14 18:31
> What would your "original understanding" provide that is useful/sensible compared to what Shane is expecting?

Nothing, as far as I can tell. I'm not really sure why I divided through by the number of records. The number of records is totally irrelevant to what we are trying to calculate here, and if we are looking for the %runtime a sum makes more sense.

**Comment by tylerjereddy** [comment] 2021-12-14 18:34
Alright, best to put that bug fix in a separate PR w/ regression test then.

**Comment by tylerjereddy** [comment] 2022-01-04 21:20
fixed by gh-595

**Closed by tylerjereddy** 2022-01-04 21:20 UTC
Labels: bug, pydarshan
