### ISSUE TITLE
BUG: PyDarshan summary report generation failure on logs with no module data

### ISSUE THREAD

**Issue by shanedsnyder** [darshan-hpc/darshan#845] opened 2022-11-02 21:05 UTC
As a prerequisite to addressing this, I'll add an empty log file to the darshan-logs repo as a test case.

When attempting to generate a summary, I get the following errors on `main`:

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/shane/software/darshan/darshan-python/darshan-util/pydarshan/darshan/__main__.py", line 3, in <module>
    main()
  File "/home/shane/software/darshan/darshan-python/darshan-util/pydarshan/darshan/cli/__init__.py", line 164, in main
    mod.main(args)
  File "/home/shane/software/darshan/darshan-python/darshan-util/pydarshan/darshan/cli/summary.py", line 569, in main
    report_data = ReportData(log_path=log_path)
  File "/home/shane/software/darshan/darshan-python/darshan-util/pydarshan/darshan/cli/summary.py", line 135, in __init__
    self.register_figures()
  File "/home/shane/software/darshan/darshan-python/darshan-util/pydarshan/darshan/cli/summary.py", line 425, in register_figures
    io_cost_fig = ReportFigure(**io_cost_params)
  File "/home/shane/software/darshan/darshan-python/darshan-util/pydarshan/darshan/cli/summary.py", line 73, in __init__
    self.generate_fig()
  File "/home/shane/software/darshan/darshan-python/darshan-util/pydarshan/darshan/cli/summary.py", line 100, in generate_fig
    fig = self.fig_func(**self.fig_args)
  File "/home/shane/software/darshan/darshan-python/darshan-util/pydarshan/darshan/experimental/plots/plot_io_cost.py", line 154, in plot_io_cost
    io_cost_df.plot.bar(stacked=True, rot=0, ax=ax_raw, legend=False, zorder=3)
  File "/home/shane/software/darshan/darshan-python/venv/lib/python3.8/site-packages/pandas/plotting/_core.py", line 1159, in bar
    return self(kind="bar", x=x, y=y, **kwargs)
  File "/home/shane/software/darshan/darshan-python/venv/lib/python3.8/site-packages/pandas/plotting/_core.py", line 1000, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
  File "/home/shane/software/darshan/darshan-python/venv/lib/python3.8/site-packages/pandas/plotting/_matplotlib/__init__.py", line 71, in plot
    plot_obj.generate()
  File "/home/shane/software/darshan/darshan-python/venv/lib/python3.8/site-packages/pandas/plotting/_matplotlib/core.py", line 450, in generate
    self._compute_plot_data()
  File "/home/shane/software/darshan/darshan-python/venv/lib/python3.8/site-packages/pandas/plotting/_matplotlib/core.py", line 635, in _compute_plot_data
    raise TypeError("no numeric data to plot")
TypeError: no numeric data to plot
```

**Comment by shanedsnyder** [comment] 2022-11-02 21:06
In cases where the log has no module data, we should just generate the portions of the report that give details on job metadata, then probably issue a warning message to notify the user no data was captured.

**Comment by tylerjereddy** [comment] 2022-11-02 23:53
I think this is a duplicate of gh-734 if you look at the traceback there. It was an accidentally empty log file--I think I shared the log file there too.

**Closed** 2023-02-27 23:56 UTC
