### ISSUE TITLE
BUG: heatmap anomalies for `snyder_acme.exe_id1253318_9-27-24239-1515303144625770178_2.darshan`

### ISSUE THREAD

**Issue by nawtrey** [darshan-hpc/darshan#576] opened 2021-12-02 23:38 UTC
@treddy highlighted some interesting behavior when generating the DXT heat maps for `snyder_acme.exe_id1253318_9-27-24239-1515303144625770178_2.darshan` (shown below). His original [comment](https://github.com/darshan-hpc/darshan/pull/570#pullrequestreview-820567121). 

It appears we have a few features to explain:
 - Why do the horizontal sums appear to be disproportionate to the activity shown in the heatmap? (Tyler's original question). Specifically, why, in the `DXT_POSIX` plot, do we see 2 ranks with almost identical activity but different horizontal sums?
 - Why are the rank counts different between the plots? 

![image](https://user-images.githubusercontent.com/46797896/144519634-164e7809-1228-45f8-803b-aab49c21536e.png)

**Comment by tylerjereddy** [comment] 2022-02-10 22:35
gh-622 should have fixed the rank counts, but not likely the resolution issues

**Comment by tylerjereddy** [comment] 2022-02-10 22:49
The issue is called `DXT heatmap vertical bar graph inconsistency` and seems to focus on the vertical bar issues, but I've added a comment to encapsulate the horizontal issues as well for the case that originally concerned me: https://github.com/darshan-hpc/darshan/issues/630#issuecomment-1035610509

I'll close this and then then that issue can be used to address the issue along both axes then

**Closed by tylerjereddy** 2022-02-10 22:49 UTC
Labels: bug, pydarshan
