### ISSUE TITLE
ENH: support for "mangled"/cythonized h5py bindings

### ISSUE THREAD

**Issue by tylerjereddy** [darshan-hpc/darshan#690] opened 2022-03-09 22:51 UTC
`h5py` uses Cython to generate C code, which then calls HDF5 C functions. Although I'm not 100 % sure this is the problem described for HDF5 read-invisibility in gh-663, a sample wrapped symbol that I see in a local build is `__real___pyx_f_4h5py_4defs_H5Dread` instead of `H5Dread`.

I started hacking on trying to capture those `H5D` cythonized read events (see below the fold), but that is getting into the runtime/C binding weeds.

<details>

 ```diff
diff --git a/darshan-runtime/lib/darshan-hdf5.c b/darshan-runtime/lib/darshan-hdf5.c
index 50d9694..dd18a4b 100644
--- a/darshan-runtime/lib/darshan-hdf5.c
+++ b/darshan-runtime/lib/darshan-hdf5.c
@@ -40,7 +40,7 @@ DARSHAN_FORWARD_DECL(H5Dcreate1, hid_t, (hid_t loc_id, const char *name, hid_t t
 DARSHAN_FORWARD_DECL(H5Dcreate2, hid_t, (hid_t loc_id, const char *name, hid_t dtype_id, hid_t space_id, hid_t lcpl_id, hid_t dcpl_id, hid_t dapl_id));
 DARSHAN_FORWARD_DECL(H5Dopen1, hid_t, (hid_t loc_id, const char *name));
 DARSHAN_FORWARD_DECL(H5Dopen2, hid_t, (hid_t loc_id, const char *name, hid_t dapl_id));
-DARSHAN_FORWARD_DECL(H5Dread, herr_t, (hid_t dataset_id, hid_t mem_type_id, hid_t mem_space_id, hid_t file_space_id, hid_t xfer_plist_id, void * buf));
+DARSHAN_FORWARD_DECL(__pyx_f_4h5py_4defs_H5Dread, herr_t, (hid_t dataset_id, hid_t mem_type_id, hid_t mem_space_id, hid_t file_space_id, hid_t xfer_plist_id, void * buf));
 DARSHAN_FORWARD_DECL(H5Dwrite, herr_t, (hid_t dataset_id, hid_t mem_type_id, hid_t mem_space_id, hid_t file_space_id, hid_t xfer_plist_id, const void * buf));
 #ifdef DARSHAN_HDF5_VERS_1_10_PLUS
 DARSHAN_FORWARD_DECL(H5Dflush, herr_t, (hid_t dataset_id));
@@ -619,7 +619,7 @@ hid_t DARSHAN_DECL(H5Dopen2)(hid_t loc_id, const char *name, hid_t dapl_id)
     return(ret);
 }
 
-herr_t DARSHAN_DECL(H5Dread)(hid_t dataset_id, hid_t mem_type_id, hid_t mem_space_id,
+herr_t DARSHAN_DECL(__pyx_f_4h5py_4defs_H5Dread)(hid_t dataset_id, hid_t mem_type_id, hid_t mem_space_id,
     hid_t file_space_id, hid_t xfer_plist_id, void * buf)
 {
     struct hdf5_dataset_record_ref *rec_ref;
@@ -637,10 +637,10 @@ herr_t DARSHAN_DECL(H5Dread)(hid_t dataset_id, hid_t mem_type_id, hid_t mem_spac
     double tm1, tm2, elapsed;
     herr_t ret;
 
-    MAP_OR_FAIL(H5Dread);
+    MAP_OR_FAIL(__pyx_f_4h5py_4defs_H5Dread);
 
     tm1 = HDF5_WTIME();
-    ret = __real_H5Dread(dataset_id, mem_type_id, mem_space_id, file_space_id,
+    ret = __real___pyx_f_4h5py_4defs_H5Dread(dataset_id, mem_type_id, mem_space_id, file_space_id,
         xfer_plist_id, buf);
     tm2 = HDF5_WTIME();
 
diff --git a/darshan-runtime/share/ld-opts/darshan-hdf5-ld-opts.in b/darshan-runtime/share/ld-opts/darshan-hdf5-ld-opts.in
index 6e5070b..c4b2eb7 100644
--- a/darshan-runtime/share/ld-opts/darshan-hdf5-ld-opts.in
+++ b/darshan-runtime/share/ld-opts/darshan-hdf5-ld-opts.in
@@ -7,7 +7,7 @@
 --wrap=H5Dcreate2
 --wrap=H5Dopen1
 --wrap=H5Dopen2
---wrap=H5Dread
+--wrap=__pyx_f_4h5py_4defs_H5Dread
 --wrap=H5Dwrite
 --wrap=H5Dclose
 @DARSHAN_HDF5_ADD_DFLUSH_LD_OPTS@
```

</details>

Actually the runtime seemed to do just fine with my hack, but I think I may need other adjustments for that testing to get output to log format appropriately?

I don't know if the symbol set that is generated is stable enough to hardcode or if it could change with Cython versions--if this is the real problem may be worth looking into.

**Comment by tylerjereddy** [comment] 2022-03-09 22:54
Only problem with this hypothesis--other things like writing also get wrapped by Cython it seems, so why do they get monitored by the runtime and reads not?

**Comment by tylerjereddy** [comment] 2022-03-10 02:52
I sprinkled prints into the Cython code and found only one location where we get read calls for the reproducers Nik and I have:

```
** before H5Dread in _proxy.pyx line 112
** after H5Dread in _proxy.pyx line 112
** before H5Dread in _proxy.pyx line 112
** after H5Dread in _proxy.pyx line 112
** before H5Dread in _proxy.pyx line 112
** after H5Dread in _proxy.pyx line 112
<snip>
```

That corresponds to this location in the Cython source: https://github.com/h5py/h5py/blob/master/h5py/_proxy.pyx#L112

In the generated C:

```C
2707         /* "h5py/_proxy.pyx":113
2708  *             if read:
2709  *                 print("** before H5Dread in _proxy.pyx line 112")
2710  *                 H5Dread(dset, mtype, mspace, fspace, dxpl, progbuf)             # <<<<<<<<<<<<<<
2711  *                 print("** after H5Dread in _proxy.pyx line 112")
2712  *             else:
2713  */
2714         __pyx_t_5 = __pyx_f_4h5py_4defs_H5Dread(__pyx_v_dset, __pyx_v_mtype, __pyx_v_mspace, __pyx_v_fspace, __pyx_v_dxpl, __pyx_v_progbuf); if (unlikely(__pyx_t_5 == ((herr_t)((herr_t)-1L)))) __PYX_ERR(0, 113, __pyx_L4_error)
```

Of course the remapping for write looks similar:

```C
2737       /* "h5py/_proxy.pyx":116
2738  *                 print("** after H5Dread in _proxy.pyx line 112")
2739  *             else:
2740  *                 H5Dwrite(dset, mtype, mspace, fspace, dxpl, progbuf)             # <<<<<<<<<<<<<<
2741  *         else:
2742  * 
2743  */
2744       /*else*/ {
2745         __pyx_t_5 = __pyx_f_4h5py_4defs_H5Dwrite(__pyx_v_dset, __pyx_v_mtype, __pyx_v_mspace, __pyx_v_fspace, __pyx_v_dxpl, __pyx_v_progbuf); if (unlikely(__pyx_t_5 == ((herr_t)((herr_t)-1L)))) __PYX_ERR(0, 116, __pyx_L4_error)
```

**Comment by tylerjereddy** [comment] 2022-03-17 00:24
Phil suggested trying `LD_DEBUG` environment variable when I asked about a way to "trace" symbol calls. It is worth a try if we could `grep` for things like `H5Dread`.

**Comment by tylerjereddy** [comment] 2022-03-23 20:30
Here are some grepped results with `LD_DEBUG`:

`mpirun -x DXT_ENABLE_IO_TRACE=1 -x LD_DEBUG=all -x DARSHAN_LOGPATH=/yellow/users/treddy/generated_darshan_logs -x DARSHAN_DISABLE_SHARED_REDUCTION=1 -x LD_PRELOAD=/yellow/users/treddy/darshan_install/lib/libdarshan.so:/usr/projects/hpcsoft/toss3/snow/hdf5/1.10.7_gcc-9.3.0_openmpi-3.1.6/lib/libhdf5.so -np 1 python3 test.py >& output.txt`

<details>
<summary> For the small `h5py` script below the fold</summary>

```python
from mpi4py import MPI
import numpy as np
from numpy.testing import assert_array_equal
import h5py

def main():
    comm = MPI.COMM_WORLD
    rank = comm.Get_rank()

    # round trip HDF5 IO test
    file_path = f"./test_rank_{rank}.hdf5"
    n_bytes = 10 * (rank + 1)

    bytes_to_write = np.ones(shape=n_bytes, dtype=np.int8)

    with h5py.File(file_path, "w") as f:
        f.create_dataset("dataset", data=bytes_to_write)

    with h5py.File(file_path, "r") as g:
        retrieved_data = np.asarray(g['dataset'])
        assert_array_equal(retrieved_data, bytes_to_write)

if __name__ == "__main__":
    main()
```

</details>

```
[py38_venv] [treddy@sn352 issue_663]$ grep -E -i 'H5Dread' output.txt
     14491:	symbol=__real_H5Dread;  lookup in file=python3 [0]
     14491:	symbol=__real_H5Dread;  lookup in file=/yellow/users/treddy/darshan_install/lib/libdarshan.so [0]
     14491:	binding file /yellow/users/treddy/darshan_install/lib/libdarshan.so [0] to /yellow/users/treddy/darshan_install/lib/libdarshan.so [0]: normal symbol `__real_H5Dread'
     14491:	symbol=H5Dread_chunk;  lookup in file=python3 [0]
     14491:	symbol=H5Dread_chunk;  lookup in file=/yellow/users/treddy/darshan_install/lib/libdarshan.so [0]
     14491:	symbol=H5Dread_chunk;  lookup in file=/usr/projects/hpcsoft/toss3/snow/hdf5/1.10.7_gcc-9.3.0_openmpi-3.1.6/lib/libhdf5.so [0]
     14491:	binding file /usr/projects/hpcsoft/toss3/snow/hdf5/1.10.7_gcc-9.3.0_openmpi-3.1.6/lib/libhdf5_hl.so.100 [0] to /usr/projects/hpcsoft/toss3/snow/hdf5/1.10.7_gcc-9.3.0_openmpi-3.1.6/lib/libhdf5.so [0]: normal symbol `H5Dread_chunk'
     14491:	symbol=H5Dread;  lookup in file=python3 [0]
     14491:	symbol=H5Dread;  lookup in file=/yellow/users/treddy/darshan_install/lib/libdarshan.so [0]
     14491:	binding file /usr/projects/hpcsoft/toss3/snow/hdf5/1.10.7_gcc-9.3.0_openmpi-3.1.6/lib/libhdf5_hl.so.100 [0] to /yellow/users/treddy/darshan_install/lib/libdarshan.so [0]: normal symbol `H5Dread'
     14491:	symbol=H5Dread;  lookup in file=python3 [0]
     14491:	symbol=H5Dread;  lookup in file=/yellow/users/treddy/darshan_install/lib/libdarshan.so [0]
     14491:	binding file /users/treddy/py38_venv/lib/python3.8/site-packages/h5py/defs.cpython-38-x86_64-linux-gnu.so [0] to /yellow/users/treddy/darshan_install/lib/libdarshan.so [0]: normal symbol `H5Dread'
     14491:	symbol=H5Dread_chunk;  lookup in file=python3 [0]
     14491:	symbol=H5Dread_chunk;  lookup in file=/yellow/users/treddy/darshan_install/lib/libdarshan.so [0]
     14491:	symbol=H5Dread_chunk;  lookup in file=/usr/projects/hpcsoft/toss3/snow/hdf5/1.10.7_gcc-9.3.0_openmpi-3.1.6/lib/libhdf5.so [0]
     14491:	binding file /users/treddy/py38_venv/lib/python3.8/site-packages/h5py/defs.cpython-38-x86_64-linux-gnu.so [0] to /usr/projects/hpcsoft/toss3/snow/hdf5/1.10.7_gcc-9.3.0_openmpi-3.1.6/lib/libhdf5.so [0]: normal symbol `H5Dread_chunk'
** before H5Dread in _proxy.pyx line 112
     14491:	symbol=H5Dread;  lookup in file=/usr/projects/hpcsoft/toss3/snow/hdf5/1.10.7_gcc-9.3.0_openmpi-3.1.6/lib/libhdf5.so [0]
     14491:	binding file /yellow/users/treddy/darshan_install/lib/libdarshan.so [0] to /usr/projects/hpcsoft/toss3/snow/hdf5/1.10.7_gcc-9.3.0_openmpi-3.1.6/lib/libhdf5.so [0]: normal symbol `H5Dread'
** after H5Dread in _proxy.pyx line 112
```

So, maybe I should check if `H5Dread_chunk` hacked into runtime tracking does the trick, just in case that is the issue..

**Comment by tylerjereddy** [comment] 2022-03-23 22:01
I think that requires deeper C code changes because the call signature of `H5Dread_chunk` differs from plain `H5D_read`. Worth checking at some point maybe though.

**Comment by carns** [comment] 2022-03-29 17:47
Thanks @tylerjereddy .  That is interesting that there are (uninstrumented; the libdarshan.so symbol lookup fails) calls to H5Dread_chunk() issued directly from Python space, and that they follow calls to H5Dread().  I wonder if it's possible that h5py issues an H5Dread() with a particular set of parameters and then falls through to H5Dread_chunk() if that fails some sort of test.  The Darshan wrappers do not record anything about H5Dread if it returns an error code.

**Comment by shanedsnyder** [comment] 2022-03-30 21:11
I was working towards reproducing this and digging deeper, then realized I don't fundamentally understand exactly how you guys are getting Darshan instrumentation in these cases.

How are you configuring Darshan, in terms of what HDF5 library you are using? Looks like above you are LD_PRELOADing both Darshan and an HDF5 library, but it looks like the HDF5 library is something provided on your system. I'm guessing that's the same HDF5 install prefix you provided for Darshan when building?

I ask because h5py ships with it's own HDF5 libraries, and I'm not sure we want to be mixing and matching the ones coming with the wheel vs those that are provided by the system. I tried doing something similar on my laptop, where I preloaded Darshan's library as well as my own personal install of HDF5 (C library, not h5py), but then tried to instrument an h5py python app and I hit errors, as I suspected:
```
(venv) shane@shane-x1-carbon /tmp/darshan (pydarshan-devel) $ ./h5test.py 
/tmp/darshan/darshan-util/venv/lib/python3.8/site-packages/h5py/__init__.py:36: UserWarning: h5py is running against HDF5 1.12.0 when it was built against 1.12.1, this may cause problems
  _warn(("h5py is running against HDF5 {0} when it was built against {1}, "
Warning! ***HDF5 library version mismatched error***
The HDF5 header files used to compile this application do not match
the version used by the HDF5 library to which this application is linked.
Data corruption or segmentation faults may occur if the application continues.
This can happen when an application was compiled by one version of HDF5 but
linked with a different version of static or shared HDF5 library.
You should recompile the application or check your shared library related
settings such as 'LD_LIBRARY_PATH'.
You can, at your own risk, disable this warning by setting the environment
variable 'HDF5_DISABLE_VERSION_CHECK' to a value of '1'.
Setting it to 2 or higher will suppress the warning messages totally.
Headers are 1.12.1, library is 1.12.0
```

Mostly just curious about what route you guys went to get any sort of instrumentation working and if you ran into any problems like this?

**Comment by tylerjereddy** [comment] 2022-03-30 21:52
> I'm guessing that's the same HDF5 install prefix you provided for Darshan when building?

Yes, there's a sample hdf5-enabled darshan runtime compile command in logs repo here (for LANL `snow` supercomputer): https://github.com/darshan-hpc/darshan-logs/tree/main/darshan_logs/runtime_and_dxt_heatmaps_diagonal_write_only

At least for me, it should have been the same parallel hdf5 shared object leveraged throughout the stack. For building `h5py` on the `snow` supercomputer from source:

- `setenv CC mpicc`
- `setenv HDF5_MPI "ON" `
- `setenv HDF5_DIR /usr/projects/hpcsoft/toss3/snow/hdf5/1.10.7_gcc-9.3.0_openmpi-3.1.6/`
- `python3 -m pip install . --no-build-isolation `

Without the extra hdf5 preload at (darshan-monitored) runtime, I observed `python3: symbol lookup error: /yellow/users/treddy/darshan_install/lib/libdarshan.so: undefined symbol: H5get_libversion `.

The process was fairly problematic until I was strict about specifying the exact hdf5 root path for pretty much the entire stack. If you load that specific hdf5 shared object first (before dashan runtime shared obj), you'll be missing all of the symbol captures for HDF5. If `h5py` were still using its own separate lib, I would have expected that to still get captured, but I didn't observe that.

If it isn't safe to first load the darshan runtime `.so` and then the specific `libhdf5.so`, I'm not sure what else you can reasonably expect a Python developer to do in these situations.

**Comment by shanedsnyder** [comment] 2022-03-30 22:06
I see, thanks a lot for the info. It hadn't occurred to me you could provide your own underlying HDF5 lib to h5py but that sounds convenient. I'll try to document some of this in our runtime documentation in case anyone else tries wants to try it out -- I haven't received much if any user requests related to h5py+darshan, but seems likely users would struggle with it.

I'll see if I can get further with the approach you used above.

**Comment by tylerjereddy** [comment] 2022-06-05 15:53
So, I've confirmed the [upstream report](https://github.com/h5py/h5py/issues/2107#issuecomment-1146758418) that `h5py` is indeed using `H5Oopen` to open HDF5 files for the cases we are studying. I'll add some thoughts on how I might like to see this handled below, if only to stimulate some discussion/thought on this.

1. Perhaps `darshan` could use the "object identifier" returned by `H5Oopen` to create some kind of record, I'm not sure, but we don't currently track the `H5O` module/interface in any way. It might depend on the relationship, if any, between an "object identifier" and a "dataset identifier" used in `H5D`. What I do think needs to change, to echo the spirit of the changes in gh-750, is that we clearly cannot make assumptions about the order in which HDF5 API functions get called--I maintain the argument that the macro `H5D_RECORD_OPEN` should not be automatically incrementing `H5D_OPENS`, and probably a few other things, because it is now clear that there are **non** `H5D` module routes to properly setup for an `H5Dread` type event. The idea that `H5Dread()` type events are inextricably linked to `H5Dopen()` or create-type API calls seems problematic--even if this is the "normal" or "best" practice, clearly `h5py` isn't doing that, and part of our objective is to inform on what actually happened with the IO calls rather than assuming a specific chain of conventional calls, right?
2. I don't think we should only adjust for this single scenario, but rather, we should increment counters at the point of the symbol capture event--if you see an `H5Dread` with no prior `H5Dopen()` (or similar), you should increment the read counter for `H5D` but not assume anything beyond that about the control flow used to get to that point. This should provide improved resilience against unanticipated control flow/usage of HDF5 API while still counting symbols. I don't really have a strong view on whether we should start tracking/reporting tables of `H5O` API calls at this time, but I do think we should not mixin calls to `H5Oopen` with the generic `H5D_OPENS` counter. I can see the argument for combining all `H5D` calls that "open" or "create" a dataset into that counter, but to me it seems a bit deceptive to start mixing the counters between the different API modules.
3. This level of refactoring worries me a bit without some testing in the CI that flushes full cycles of the runtime right through to the Python bindings. There is a [`pytest-mpi`](https://pytest-mpi.readthedocs.io/en/latest/usage.html) plugin, and if we really want to be robust in making sure we handle the extremely wide variety of profiling scenarios that could arise, I'm not sure how much longer we can safely avoid "functional" testing of the runtime right through to the structures of the logs it produces for a given toy/test program.

**Comment by shanedsnyder** [comment] 2022-06-07 19:45
Cool, I'm glad we have some closure on what exactly was responsible for opening datasets. I'm not exactly sure why h5py prefers the `H5Oopen` call -- it seems basically identical to `H5Dopen`, just that it is more generic. In any case, I think we could probably support it with some tinkering.

First, I'm assuming that whatever dataset ID returned by `H5Oopen` would be identical to what you would get from `H5Dopen` -- I don't see any reason why HDF5 would need a more generic object ID for these things and hassle with maintaining the mappings to the more specific thing (e.g., a dataset object). If that's the case, I think all we need to do is just intercept `H5Oopen`, and have it set up the open dataset information via H5D_OPEN macro, so subsequent dataset read/write calls know what dataset corresponds to the given identifier. I guess you could argue it's misleading to increment an H5D_OPEN counter based on a call to an H5O API, but I think it's actually okay -- at the API level that's true, but at the conceptual I/O level, it's the same thing in that it is opening an HDF5 dataset for reading/writing, which is what we really care about. The one missing technical piece that stands out to me above is the ability to determine whether a given object referenced in `H5Oopen` is a dataset. We only care about datasets and don't want to maintain runtime state for attributes, links, and other HDF5 constructs.

Deferring the incrementing of open counters to the read/write functions is probably not exactly what we want either. For one, it ignores that we also capture timing information on when things are first/last opened (and how long they took, which is associated with META time). Similarly, users could actually be opening/closing the dataset many times without doing I/O and we wouldn't be able to capture this information. Generally speaking, our lives will be easier if we just make sure we are properly instrumenting the open calls as they happen.

BTW, thanks for the pointer on pytest-mpi. I think you're right that we could use something like that to implement a more thorough end-to-end testing framework for catching bugs across runtime and util libraries, as well as the python bindings. This is something we definitely have more interest in improving, just has been hard to make time to prioritize it. Hopefully soon.

**Comment by tylerjereddy** [comment] 2022-06-07 21:40
Ok, I'll close my PR and leave this up to the team--FWIW, I do think we should be a bit more modular with counters to get fine-grained API event information vs. assuming event chains. I thought it would have been possible to capture the timing information either way, it would just require a more invasive rewrite.

**Comment by shanedsnyder** [comment] 2022-06-08 16:22
I just opened a new PR (#751) that hopefully allows this to work for your h5py test case.

In general, with respect to HDF5 instrumentation, we've just decided to focus exclusively on APIs that have I/O impacts that are worth understanding. The HDF5 API is pretty massive, and we definitely don't want to intercept and store counters for every call -- things like `H5T` for creating new datatypes for the library or `H5A` for associating attributes with files or other objects are just not that interesting from an I/O perspective, so makes sense to mostly ignore.

I agree that in general we should be careful in what we are assuming inside of Darshan, though. But in this case, I think it's fine to assume that a dataset being accessed by `H5Dwrite`/`H5Dread` has been opened prior (that's probably strictly required, actually) -- it's just that I did not know there was a generic H5O API for producing an open dataset.

**Comment by shanedsnyder** [comment] 2023-03-02 22:11
I'll close this, as the underlying issue has been resolved for awhile now. I doubt there are any other alternatives for getting open dataset references from HDF5 beyond `H5Dopen`/`H5Dcreate`/`H5Oopen`, so I'd expect us to be covered here going forward. If something else pops up, we can add instrumentation of more HDF5 APIs, but as it stands I don't think we need to take on more general instrumentation of HDF5.

**Closed by shanedsnyder** 2023-03-02 22:11 UTC
Labels: enhancement
